### ISSUE TITLE
Allow third party downloads.

### ISSUE THREAD

**Issue by drakosoldier298** [ArvemW/Sky-Origins#4]
![image](https://user-images.githubusercontent.com/30358222/178088898-eef02cd0-0984-40b8-b2af-91b3ba089603.png)
This toggle allows polymc/multimc and other non curseforge launchers to download your curseforge mod, aka no more forcing users to play on curseforge launcher

**Comment by ArvemW** [comment]
You don't have to use CurseForge as the launcher. You can simply copy the .jar file into the mods folder.

**Comment by drakosoldier298** [comment]
THis is true but for creatign a modpack for any l;launcher into on curseforge. such as using packwiz or for a modpack in general if someone tries to download said pack when not using curseforge it will fail because of this issue.

**Comment by ArvemW** [comment]
Fair enough, I'll change it.
